#' River Network Smooths
#'
#' For data observed over river networks, a simple river network smoother can be
#' appropriate. These functions provide such a smoother class for mgcv.
#'
#' @param object For the smooth.construct method a smooth specification object,
#'   usually generated by a term s(x,...,bs="rn", xt=list(polys=foo)). x is a
#'   factor variable giving labels for geographic districts, and the xt argument
#'   is obligatory: see details. For the Predict.Matrix method an object of class
#'   "rn.smooth" produced by the smooth.construct method.
#' @param data a list containing just the data (including any by variable)
#'   required by this term, with names corresponding to object$term
#'   (and object$by). The by variable is the last element.
#'
#' @return
#' An object of class "rn.smooth" or a matrix mapping the coefficients of the
#' river network smooth to the predictions for the nodes listed in data.
#'
#' @importFrom mgcv Predict.matrix
#' @exportS3Method mgcv::Predict.matrix rn.smooth
Predict.matrix.rn.smooth <- function (object, data)
{
  X <- object$xt$X[,ncol(object$xt$X) - object$bs.dim:1 + 1]

  X[data[[object$term]],]
}